import './index.css';
import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {MapContainer, TileLayer, Marker, Popup, useMapEvents} from 'react-leaflet';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';

L.Icon.Default.mergeOptions({
  iconRetinaUrl:'https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon-2x.png',
  iconUrl:'https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png',
  shadowUrl:'https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png'
});
const API=import.meta.env.VITE_API||'http://localhost:8000';
const emptyForm={title:'',description:'',latitude:13.0827,longitude:80.2707,address:'',district:'Chennai',people_affected:0};
function Pin({onPick}){useMapEvents({click:e=>onPick(e.latlng)});return null}
async function api(path,opts){const r=await fetch(API+path,opts);const data=await r.json();if(!r.ok)throw new Error(data.detail||'Request failed');return data}
function App(){
 const [tab,setTab]=useState('dashboard'),[problems,setProblems]=useState([]),[clusters,setClusters]=useState([]),[stats,setStats]=useState({}),[form,setForm]=useState(emptyForm),[msg,setMsg]=useState(''),[loading,setLoading]=useState(false),[filters,setFilters]=useState({domain:'',severity:'',status:'',q:''}),[selected,setSelected]=useState(null);
 const load=async()=>{try{setLoading(true);const params=new URLSearchParams(Object.fromEntries(Object.entries(filters).filter(([,v])=>v)));const [p,s,c]=await Promise.all([api('/api/problems?'+params),api('/api/stats'),api('/api/clusters')]);setProblems(p);setStats(s);setClusters(c)}catch(e){setMsg(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[filters.domain,filters.severity,filters.status,filters.q]);
 const locate=()=>navigator.geolocation?.getCurrentPosition(p=>{setForm(f=>({...f,latitude:+p.coords.latitude.toFixed(6),longitude:+p.coords.longitude.toFixed(6)}));setMsg('GPS location captured.')},()=>setMsg('Location permission was not available.'));
 const submit=async e=>{e.preventDefault();try{setLoading(true);const p=await api('/api/problems',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,people_affected:+form.people_affected})});setMsg(`Reported successfully. AI classified it as ${p.domain} / ${p.severity}.`);setForm(emptyForm);setTab('problems');load()}catch(e){setMsg(e.message)}finally{setLoading(false)}};
 const seed=async()=>{try{const x=await api('/api/seed',{method:'POST'});setMsg(x.message||`Seeded ${x.count} demo problems.`);load()}catch(e){setMsg(e.message)}};
 const runFusion=async id=>{try{const x=await api('/api/fusion/run/'+id,{method:'POST'});setMsg(x.fused?`SOLVRA found ${x.members} related reports and created a systemic cluster.`:x.message);load()}catch(e){setMsg(e.message)}};
 const updateStatus=async(id,status)=>{try{await api(`/api/problems/${id}/status?status=${status}`,{method:'PATCH'});setMsg(`Status changed to ${status}.`);load();}catch(e){setMsg(e.message)}};
 return <div className="app">
  <header><div className="brand"><div className="logo">S</div><div><b>SOLVRA</b><small>Problem Intelligence Platform</small></div></div><nav>{[['dashboard','Dashboard'],['report','Report'],['map','Live Map'],['problems','Problems'],['clusters','Clusters']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav></header>
  {msg&&<div className="toast">{msg}<button onClick={()=>setMsg('')}>×</button></div>}
  <main>
   {tab==='dashboard'&&<Dashboard stats={stats} problems={problems} clusters={clusters} onSeed={seed} onMap={()=>setTab('map')} onReport={()=>setTab('report')} />}
   {tab==='report'&&<Report form={form} setForm={setForm} submit={submit} locate={locate} loading={loading}/>} 
   {tab==='map'&&<MapPage problems={problems} form={form} setForm={setForm} />}
   {tab==='problems'&&<Problems problems={problems} filters={filters} setFilters={setFilters} loading={loading} onFusion={runFusion} onSelect={setSelected} onStatus={updateStatus}/>} 
   {tab==='clusters'&&<Clusters clusters={clusters} onFusion={()=>problems[0]&&runFusion(problems[0].id)} onSelect={async c=>setSelected(await api('/api/clusters/'+c.id))}/>} 
  </main>
  {selected&&<Modal data={selected} close={()=>setSelected(null)} />}
 </div>
}
function Dashboard({stats,problems,clusters,onSeed,onMap,onReport}){return <><section className="hero"><div><p className="eyebrow">AI + GEO + COMMUNITY INTELLIGENCE</p><h1>Turn scattered problems into <span>actionable systems.</span></h1><p>Report a local issue, capture its exact location, let SOLVRA classify it, then fuse related reports to reveal systemic patterns.</p><div className="actions"><button className="primary" onClick={onReport}>Start reporting</button><button onClick={onMap}>Explore live map</button><button onClick={onSeed}>Load demo data</button></div></div><div className="hero-card"><strong>Fusion intelligence</strong><div className="flow"><span>Reports</span><i>→</i><span>AI Analysis</span><i>→</i><span>Geo Fusion</span><i>→</i><span>Cluster</span></div><small>Semantic + geographic + urgency signals create a coordinated problem view.</small></div></section><div className="cards"><Card t="Total Problems" v={stats.total_problems||0}/><Card t="High Priority" v={stats.high_priority||0}/><Card t="Fused Reports" v={stats.fused||0}/><Card t="People Affected" v={stats.people_affected||0}/><Card t="Systemic Clusters" v={stats.clusters||clusters.length||0}/></div><div className="grid2"><section className="panel"><h2>Domain distribution</h2>{Object.entries(stats.domains||{}).map(([d,n])=><div className="bar" key={d}><span>{d}</span><div><i style={{width:`${stats.total_problems?Math.max(4,n/stats.total_problems*100):0}%`}}/></div><b>{n}</b></div>)}</section><section className="panel"><h2>Recent reports</h2>{problems.slice(0,5).map(p=><div className="mini" key={p.id}><b>{p.title}</b><span>{p.domain} · {p.severity}</span></div>)}</section></div></>}
function Card({t,v}){return <div className="card"><span>{t}</span><strong>{v.toLocaleString?.()||v}</strong></div>}
function Report({form,setForm,submit,locate,loading}){const f=(k,v)=>setForm({...form,[k]:v});return <section><div className="section-head"><div><p className="eyebrow">GEOTAGGED COMMUNITY REPORT</p><h1>Report a Problem</h1><p>Every report becomes structured intelligence for SOLVRA.</p></div></div><form className="form" onSubmit={submit}><label>Problem title<input value={form.title} onChange={e=>f('title',e.target.value)} placeholder="e.g. Groundwater shortage affecting farmers" required/></label><label>Description<textarea value={form.description} onChange={e=>f('description',e.target.value)} placeholder="Explain what is happening, who is affected and how urgent it is..." required/></label><div className="form-grid"><label>Latitude<input type="number" step="any" value={form.latitude} onChange={e=>f('latitude',+e.target.value)}/></label><label>Longitude<input type="number" step="any" value={form.longitude} onChange={e=>f('longitude',+e.target.value)}/></label><label>District<input value={form.district||''} onChange={e=>f('district',e.target.value)} placeholder="District"/></label><label>People affected<input type="number" min="0" value={form.people_affected} onChange={e=>f('people_affected',e.target.value)}/></label></div><label>Address / landmark<input value={form.address||''} onChange={e=>f('address',e.target.value)} placeholder="Street, village, landmark..."/></label><div className="actions"><button type="button" onClick={locate}>Use my GPS</button><button className="primary" disabled={loading}>{loading?'Submitting...':'Submit problem'}</button></div></form></section>}
function MapPage({problems,form,setForm}){return <section><div className="section-head"><div><p className="eyebrow">GEOSPATIAL INTELLIGENCE</p><h1>Live Problem Map</h1><p>Click anywhere on the map to set a report location.</p></div></div><MapContainer center={[13.0827,80.2707]} zoom={11} style={{height:'68vh',borderRadius:18}}><TileLayer attribution="© OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><Pin onPick={p=>setForm(f=>({...f,latitude:+p.lat.toFixed(6),longitude:+p.lng.toFixed(6)}))}/>{problems.map(p=><Marker key={p.id} position={[p.latitude,p.longitude]}><Popup><b>{p.title}</b><br/>{p.domain} · {p.severity}<br/>{p.district||'Unknown district'}<br/>{p.people_affected||0} people affected</Popup></Marker>)}</MapContainer><div className="coordinate">Selected location: <b>{form.latitude}, {form.longitude}</b></div></section>}
function Problems({problems,filters,setFilters,loading,onFusion,onSelect,onStatus}){return <section><div className="section-head"><div><p className="eyebrow">PROBLEM REGISTRY</p><h1>All Problems</h1></div></div><div className="filters"><input placeholder="Search title, description, district" value={filters.q} onChange={e=>setFilters({...filters,q:e.target.value})}/><select value={filters.domain} onChange={e=>setFilters({...filters,domain:e.target.value})}><option value="">All domains</option>{['WATER','AGRICULTURE','HEALTHCARE','EDUCATION','SANITATION','TRANSPORT','ENERGY','ENVIRONMENT'].map(x=><option key={x}>{x}</option>)}</select><select value={filters.severity} onChange={e=>setFilters({...filters,severity:e.target.value})}><option value="">All severity</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select><select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">All status</option>{['REPORTED','VERIFIED','FUSED','IN_PROGRESS','RESOLVED'].map(x=><option key={x}>{x}</option>)}</select></div><div className="list">{loading?<p>Loading...</p>:problems.map(p=><article className="problem" key={p.id}><div><div className="tags"><span>{p.domain}</span><span className={p.severity.toLowerCase()}>{p.severity}</span><span>{p.status}</span></div><h3>{p.title}</h3><p>{p.description}</p><small>📍 {p.latitude.toFixed(5)}, {p.longitude.toFixed(5)} · {p.district||'No district'} · {p.people_affected||0} affected</small></div><div className="row-actions"><button onClick={()=>onSelect(p)}>Details</button><button onClick={()=>onFusion(p.id)}>Run fusion</button><select value={p.status} onChange={e=>onStatus(p.id,e.target.value)}><option>REPORTED</option><option>VERIFIED</option><option>FUSED</option><option>IN_PROGRESS</option><option>RESOLVED</option></select></div></article>)}{!problems.length&&<div className="empty">No problems found. Use <b>Report</b> or load demo data.</div>}</div></section>}
function Clusters({clusters,onFusion,onSelect}){return <section><div className="section-head"><div><p className="eyebrow">SYSTEMIC INTELLIGENCE</p><h1>Problem Clusters</h1><p>Clusters connect separate reports that point to the same underlying issue.</p></div><button className="primary" onClick={onFusion}>Run fusion on latest report</button></div><div className="cluster-grid">{clusters.map(c=><article className="cluster" key={c.id} onClick={()=>onSelect(c)}><div className="tags"><span>{c.domain}</span><span>{Math.round(c.confidence*100)}% confidence</span></div><h2>{c.title}</h2><p>{c.root_cause}</p><div className="cluster-foot"><b>{c.member_count} reports</b><span>View intelligence →</span></div></article>)}{!clusters.length&&<div className="empty">No clusters yet. Create a few related reports and run fusion.</div>}</div></section>}
function Modal({data,close}){return <div className="modal-bg" onClick={close}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><p className="eyebrow">INTELLIGENCE DETAIL</p><h2>{data.title}</h2>{data.domain&&<div className="tags"><span>{data.domain}</span><span>{data.severity||`${Math.round((data.confidence||0)*100)}% confidence`}</span></div>}<p>{data.description||data.root_cause}</p>{data.members&&<><h3>Cluster members</h3>{data.members.map(x=><div className="mini" key={x.id}><b>{x.title}</b><span>{x.domain} · {x.status}</span></div>)}<h3>Recommended action</h3><p>{data.recommended_action}</p></>}</div></div>}

createRoot(document.getElementById('root')).render(<App/>);
